### PR TITLE
increase in unicorn workers requires more memory

### PR DESCRIPTION
**Pull request by ultrasaurus**
increasing the number of unicorn workers requires an increase in memory
this PR makes that persistent by specifying it in the manifest

### CODE REVIEW

**Comment by ultrasaurus** [comment]
@dnesting I think this is what you need.  Feel free to merge or test locally.

**Comment by dnesting** [comment]
This looks good, though the description should say "processes" or "workers" and not "threads".  This would normally be me nitpicking but here the difference is significant and the reason I'm exploring puma.

**Comment by ultrasaurus** [comment]
this isn't covered by any tests, so gonna merge before our really-slow CI is complete

**Comment by ultrasaurus** [comment]
@dnesting thanks for the clarification. I updated the description and title

**Pull request merged**
