### PR TITLE
Index creation

### PR DESCRIPTION
**Pull request by madebydna**
Created a `DataMagic::Config.index_exists?` method to ensure that the
index only gets created once. If the index exists after the app starts
subsequent calls to  `#import_with_dictionary` and `#import_csv`
will not trigger index creation.

On the other hand, if the index is not present on app start, then
those actions will create the index.

The logs look cleaner now as they only report on index creation once. 
I'm not sure if the test coverage is sufficient and covers all possible entry points,
so let me know if more tests are needed. 

Working on issue #135

### CODE REVIEW

**Comment by yozlet** [comment]
Yay refactoring! @madebydna, is this ready to merge? :+1: from me.

**Comment by madebydna** [comment]
Thanks for the feedback @yozlet! It is ready for merging as far as I can tell.

**Comment by ultrasaurus** [comment]
thanks @madebydna -- looks good to me too!

**Comment by ultrasaurus** [comment]
oops -- meant to merge into dev, reverted master, hang on

**Comment by madebydna** [comment]
Oh dear, was I supposed to send the pull request to the `dev` branch? I was going to that but the Contributing guide says to submit the pull request to `open-data-maker:master`, so I followed that... Let me know if the docs are wrong and I'd be happy to update them.

**Comment by ultrasaurus** [comment]
oh!  need to fix the contributing guide!  Now this is committed to dev:  https://github.com/18F/open-data-maker/commit/1103e0393290932329a2d0c34f470543ec92e0f0

**Pull request merged**
