### PR TITLE
[WIP] Features/categories on homepage 46

### PR DESCRIPTION
**Pull request by slhaines**

### CODE REVIEW

**Comment by ultrasaurus** [comment]
this addresses #46 however it fails when the file doesn't have categories with:
```
NoMethodError at /
undefined method `map' for nil:NilClass
```

When I decided to use liquid, I thought it would make it easier since I thought it would make the code more like what it would be on a jekyll site that used the API.  Seeing everything it takes to get the data on the page, I'd like to explore an approach that would be closer to what a site using the API would make.

What if we did this in app.rb:
```
      render :home, layout: true, locals: {
        'title' => 'Open Data Maker',
        'endpoints' => DataMagic.config.api_endpoint_names,
        'examples' => DataMagic.config.examples,
        'categories' => DataMagic.config.data['categories'].to_json
      }
```

and then at the top of the page, somthing like:
```
<script>
 categories = {{ categories }}
</script>
```

then I think we could use Javascript to lay out the boxes for the category data.  

cc @shamus

**Comment by slhaines** [comment]
Note: I did not include the fixes to api_spec in this branch - that's probably why it's failing Travis CI.

**Comment by ultrasaurus** [comment]
hi @slhaines -- there's a bunch of data that changed.  Now that it's a fixture (not using the default sample-data), you could just remove the new fields, like ```code``` and ```id```` -- or fix the tests -- either way is fine.

**Comment by slhaines** [comment]
@ultrasaurus Can you tell me which files to remove `code` and `id` from?

**Comment by shamus** [comment]
Hi, finally a member of the world again.

Good catch @ultrasaurus.  Generally it seems like our branch is a bit out of sync from where the rest of the project is.  It seems we want to move a lot of our code (mainly the category model stuff) into the datamagic package.

There's probably some other places where we're out of step.

**Comment by slhaines** [comment]
@shamus Hi Jeremy, welcome back! I managed to fix all the api_spec failures and have added more formatting stuff which I'll rebase and push shortly. But I need help to get our code to access spec/fixtures/sample-data/data.yaml rather than sample-data/data.yaml.

**Comment by ultrasaurus** [comment]
I think this is covered by https://github.com/18F/open-data-maker/pull/209  -- if we missed anything, please submit a new PR with just that.  Thank you!

**Pull request closed without merging**
