### PR TITLE
[WIP] Data dictionary on homepage WIP

### PR DESCRIPTION
**Pull request by slhaines**
Waiting on CSS layouts and data.yaml parsing (issue 45) and data dictionary (issue 8).

### CODE REVIEW

**Comment by slhaines** [comment]
This commit starts work on issue 44, displaying the data dictionary on a URL to look like this:
https://cloud.githubusercontent.com/assets/41906/8634657/26527ca0-27b6-11e5-9384-1877d8591571.png
For now, we are simply using the home page as the URL (pending development of the Views).

**Comment by slhaines** [comment]
Jeremy and I made another commit on Issue 44 at the pair programming tonight.
We now load the categories from the data.yaml file.
We added a spec test.
An existing spec test was failing (one that looks for all the categories, so to make that one pass we temporarily removed some categories from data.yaml - just to reduce our typing for the spec test).

**Comment by ultrasaurus** [comment]
I think a sister PR was actually merged with this functionality -- need to test and verify before closing or looking at this again.  @slhaines -- do you remember?

**Comment by slhaines** [comment]
Sister PR was #209, which combined all data dictionary page display issues.

**Comment by ultrasaurus** [comment]
thanks for the note! closing this one

**Pull request closed without merging**
