### PR TITLE
adding a format string (.json or .csv) is now supported

### PR DESCRIPTION
**Pull request by cantino**
@ultrasaurus, this PR is for the work that @salogel42 and myself did last night.  You should be able to visit a dataset like /cities and append a format string to the URL.  `.json` will behave like everything does now, and `.csv` will output a csv dump of the data.

A few things:

* We didn't know padrino, so we were not sure where to put the `recursive_keys` and `recursive_fields` helper methods.
* The format code would be better extracted into a helper.  Again, we weren't sure where to put it.
* We assume all output rows will have the same keys (e.g., they're not sparse)

/cc Hey @jmcarp!

### CODE REVIEW

**Comment by cantino** [comment]
Should fix https://github.com/18F/open-data-maker/issues/48

**Comment by ultrasaurus** [comment]
Thanks @cantino and  @salogel42 !   

My current thinking is that all of the logic should go in the DataMagic library with the app just marshalling query args and rendering some views -- providing a thin API / UI layer on top of the library calls.  So I would add an option to search format:'json' and format:'csv' with json as the default.

What do you think?

**Comment by cantino** [comment]
It doesn't really seem like the DataMagic library should be in charge of serialization.  That feels like a separate concern.

**Comment by cantino** [comment]
I've extracted our helpers into a module.  @ultrasaurus, you may want to make a method that handles the serialization, or you could pull it into DataMagic.

**Comment by ultrasaurus** [comment]
I guess it seemed that DataMagic would do csv in and out, but I see your point.  Maybe we need a general library that converts csv in JSON.  I'd like less in the sinatra app, then we could create unit tests, though could live with API tests for starters :)

**Comment by ultrasaurus** [comment]
I'm working on this now... rebased to dev & running locally

**Comment by ultrasaurus** [comment]
integrated into:  https://github.com/18F/open-data-maker/pull/147 and merged!

Many thanks for all of your excellent work on this @cantino and @salogel42

**Comment by cantino** [comment]
You're very welcome, thanks for putting the event together!

**Pull request closed without merging**
