### PR TITLE
Use `_source: false` to limit JSON coming back from ES

### PR DESCRIPTION
**Pull request by yozlet**
Also, use the ES result `took` key to get the query time in ms.

### CODE REVIEW

**Comment by ultrasaurus** [comment]
tests pass but will leave extra stuff in the full request of school info:
image

I can write a quick test of that

**Comment by ultrasaurus** [comment]
tho that isn't harmful, if we want to push this and let that be a bug fix

**Comment by yozlet** [comment]
Hmm, good point... maybe I should leave the `_source: { exclude: [_*] }` in for when there isn't a `fields` param

**Comment by yozlet** [comment]
:heart:

**Pull request merged**
