### PR TITLE
Import data without data.y?ml

### PR DESCRIPTION
**Pull request by jmcarp**
I'm a fan of the data.yml standard, but some consumers of this service might not bother to provide them. In the interest of making things work with absolutely minimal inputs, this patch allows indexing to work when no data.yml file is found. @ultrasaurus, if this isn't a behavior you want to expose by default, I can add a flag like `ALLOW_MISSING_YML` that defaults to false.

Note: branched off #68.

cc @gbinal

### CODE REVIEW

**Comment by ultrasaurus** [comment]
I like the idea of making it "just work" without data.yaml, but maybe it should have a warning.  Then use the constant ```ALLOW_MISSING_YML``` to supress the warning?

**Comment by jmcarp** [comment]
@ultrasaurus: I revised #68 based on your comments (thanks for reviewing!). I like the idea of a warning that can be silenced with a flag--will add that once #68 is squared away, since this patch depends on the other one.

**Comment by jmcarp** [comment]
Warning and flag added, and merged in #68 for globbing against remote data sources.

**Comment by ultrasaurus** [comment]
@jmcarp this looks great -- sorry a bunch of my changes collided!  Could you rebase against master and push a new branch?  I *think* there's just one last thing (slugified directory name) that needs to work against s3.

**Comment by jmcarp** [comment]
Conflicts fixed, S3 buckets slugified, warning updated.

**Comment by ultrasaurus** [comment]
@jmcarp could you also update README and NOTES.md with this pull request?

**Comment by jmcarp** [comment]
@ultrasaurus docs updated.

**Comment by ultrasaurus** [comment]
replaced by https://github.com/18F/open-data-maker/pull/85

**Pull request closed without merging**
