### PR TITLE
V1 api

### PR DESCRIPTION
**Pull request by yozlet**
A fairly significant change to the REST API, to bring us in line with [White House API standards](https://github.com/WhiteHouse/api-standards). Also satisfies https://github.com/18F/college-choice/issues/495 .

 * All JSON/CSV-returning URLs now begin with `/v1`. (Apart from that, URL patterns are unchanged)
 * The `total`, `page` and `per-page1` JSON hash keys are now collected in the `metadata` hash

Not included in this PR, but coming next: proper usable errors for #152.

### CODE REVIEW

**Comment by yozlet** [comment]
@ultrasaurus, can you take a look?

**Comment by diego-** [comment]
which environments is this change currently deployed to?

**Comment by ultrasaurus** [comment]
@yozlet these look good to me.  Thanks so much for moving this forward!

**Comment by yozlet** [comment]
@diego-: It's on `dev`.

**Pull request merged**
