### PR TITLE
make a humanstxt.org acknowledging our amazing contributors #146. Bef…

### PR DESCRIPTION
**Pull request by jenjwong**
…ore this commit there was no humans.txt file recognizing contributors. This commit adds a text file recognizing contributors to date. Add button to home.liquid.

### CODE REVIEW

**Comment by jenjwong** [comment]
Hey @ultrasaurus, after talking with you tonight, we realized that there's more to do for this issue before it's ready for review. Here are the things on our todo list:
 
* create object that can fetch repo contributors and given their github handles can scrape data from their profile page
* yml file for non github contributors details
* merge github scrape & yml into humans.txt file
* create rake task that can be run as remembered or with chron job/circle ci builds

**Comment by yozlet** [comment]
Wow, that sounds like a lot of work. Any chance that someone else has written that code already?

**Comment by yozlet** [comment]
This might do the trick: https://github.com/JoahG/humans-txt-generator

**Comment by jenjwong** [comment]
Sarah was looking for a way to update both Git Hub contributors and non-Git Hub contributors easily. I'm working on a rake task that automates the process. I have 90% of the task complete and will submit soon.

**Comment by ultrasaurus** [comment]
@jenjwong do you still want to work on this rake task?  would be nice to acknowledge the humans!

**Comment by jenjwong** [comment]
I'm keen to finish the task. It's 90% complete. I start an intensive bootcamp on Monday, and will be focused on JavaScript until May.

**Comment by ultrasaurus** [comment]
@jenjwong it would be wonderful if you would be able to finish this... just to clarify, are you going to do it in Javascript?  or saying you won't be able to work on it till May?

Thanks!

**Comment by jenjwong** [comment]
I'm keen to finish the task and won't be able to work on it till May.

**Pull request closed without merging**
